## Libraries Setup

In [1]:
import pandas as pd 
import numpy as np

# BigQuery it's used to import dim_track. 
from google.cloud import bigquery
client = bigquery.Client(project='sql-sandbox-435415')

## BigQuery and csv Files import

Stored in BigQuery, dim_track is the master reference table for all track-level metadata. During the cleaning pipeline, DSP reports with missing fields (e.g. LabelName, ISRC) are enriched by joining against this table on ISRC.

In [2]:
sql_query = """
SELECT * 
from `sql-sandbox-435415.music_warehouse.dim_track`
"""

query_job = client.query(sql_query)
df_dim_track = query_job.to_dataframe()
df_dim_track.info()

<class 'pandas.DataFrame'>
RangeIndex: 103911 entries, 0 to 103910
Data columns (total 6 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Artist  103911 non-null  str
 1   Label   103911 non-null  str
 2   Track   103911 non-null  str
 3   ISRC    103911 non-null  str
 4   Album   103911 non-null  str
 5   UPC     103911 non-null  float64
dtypes: float64(1), str(5)
memory usage: 16.1 MB

---

These are all the DSP report tables used across the project:

In [3]:
df_amazon_jan24_raw = pd.read_csv('inbound_reports/amazon_jan24_raw.csv')
df_amazon_jan24_raw.head()

,ArtistName,LabelName,TrackTitle,ISRC,AlbumTitle,UPC,CountryCode,Service_Tier,PlayCount,Royalty,CurrencyCode,Period_Start,Period_End,ASIN
0,Walters & Sosa,Redeye Worldwide,Synchronized Clear-Thinking Core,DE3NL2489870,Repurpose Frictionless E-Business - EP,9.885830e+12,CO,Unlimited,118,0.26,USD,01/01/2024,31/01/2024,B0URWAW686
1,Moore and the Managers,Dead Oceans,Optional Static Support (Extended Mix),SE0DU1971111,Enhance Wireless Deliverables,6.491991e+11,JP,Unlimited,562,256.50,JPY,01/01/2024,31/01/2024,B0XYGLLL1Z
2,Gomez and the Behaviors,Gray Inc Records,Reverse-Engineered Bifurcated Synergy,FRR722046432,Brand Frictionless Applications,2.893330e+12,SE,Prime,22,0.06,USD,01/01/2024,31/01/2024,B0ERX2KYPK
3,Shannon Wilson,[PIAS],Horizontal Local Standardization,USMCK2091254,Exploit User-Centric Solutions,1.854620e+12,AU,Prime,1198,4.34,USD,01/01/2024,31/01/2024,B0RVSPJGMY
4,Sandra Owens,Moore Inc Records,Cloned System-Worthy Algorithm,NL0X12366321,Strategize Extensible Relationships,5.473460e+12,CA,Prime,548,1.71,USD,01/01/2024,31/01/2024,B0L4K9HNME

In [4]:
df_amazon_feb24_raw = pd.read_csv('inbound_reports/amazon_feb24_raw.csv')
df_amazon_feb24_raw.head()

,ArtistName,LabelName,TrackTitle,ISRC,AlbumTitle,UPC,CountryCode,Service_Tier,PlayCount,Royalty,CurrencyCode,Period_Start,Period_End,ASIN
0,Sara Guzman,Lopez Recordings,Right-Sized Local Challenge,NLKSG2310725,Target Value-Added E-Services,7.787640e+12,SE,Prime,304,1.18,USD,01/02/2024,29/02/2024,B0HS8XT4VK
1,Wilkerson and the Readys,"Roberson, Ellis and Henry Label",Versatile Interactive Hierarchy,GB6921858245,Harness Strategic Relationships,9.824450e+12,PL,Unlimited,158,0.35,USD,01/02/2024,29/02/2024,B0LWQEW166
2,Walker and the Thinks,Dim Mak Records,Multi-Tiered Global Alliance,GBOJC2378105,Aggregate Open-Source Experiences - Single,2.735920e+12,GB,Prime,685,1.56,GBP,01/02/2024,29/02/2024,B0ADRPHG0R
3,Hill & Nolan,"Pure Williams, Music",Synergistic Exuding Moderator (Extended Mix),USURC1924388,Orchestrate Interactive Users,6.392420e+12,CA,Prime,32,0.11,USD,01/02/2024,29/02/2024,B0TR6789MK
4,Big Martin,Gray Inc Records,Automated Real-Time Capability (Live),US3HF2414236,Incentivize B2C E-Commerce,8.166820e+12,SE,Prime,125,0.32,USD,01/02/2024,29/02/2024,B0A8KVB0I0

In [5]:
df_amazon_mar24_raw = pd.read_csv('inbound_reports/amazon_mar24_raw.csv')
df_amazon_mar24_raw.head()

,ArtistName,LabelName,TrackTitle,ISRC,AlbumTitle,UPC,CountryCode,Service_Tier,PlayCount,Royalty,CurrencyCode,Period_Start,Period_End,ASIN
0,Big Russo,Better Noise Music,Universal Holistic Help-Desk,SEJ0Q2077055,Morph Rich E-Tailers - EP,8.828410e+12,NL,Prime,136,0.40,EUR,01/03/2024,31/03/2024,B0VVMSOOLB
1,Schultz & Brown,"Pure Williams, Music",Advanced Disintermediate Focus Group,SEMLT2417008,Re-Intermediate User-Centric Convergence,5.224710e+12,NL,Unlimited,9,0.05,EUR,01/03/2024,31/03/2024,B07CWVAN9P
2,Pennington and the Saves,"Hunter, Sampson and Flynn Label",Pre-Emptive Executive Migration,DEBDS1963884,Disintermediate User-Centric Functionalities -...,3.679630e+12,FR,Prime,2,0.00,EUR,01/03/2024,31/03/2024,B08HDJAH1A
3,Nancy Watts,Merge Records,Triple-Buffered Zero Administration Intranet,DE9IG1889119,Re-Contextualize Value-Added Vortals,2.725900e+12,US,Unlimited,20,0.08,USD,01/03/2024,31/03/2024,B0VXJ4M2UW
4,Bright & Warren,Raw Six Records,Integrated Analyzing Model,DEH5G2136029,Revolutionize Collaborative Methodologies,4.912800e+12,IT,Prime,1,0.00,EUR,01/03/2024,31/03/2024,B0F6TNHXXS

In [6]:
df_apple_jan24_raw = pd.read_csv('inbound_reports/apple_jan24_raw.csv')
df_apple_jan24_raw.head()

,Artist,Label,Song_Title,ISRC,Album,UPC,Territory,Subscription_Type,Plays,Earnings,Currency_Code,Report_Start_Date,Report_End_Date,Apple_ID
0,Luna & Cervantes,Pure Conway-David Records,Front-Line Multi-Tasking Paradigm,SER6N2360724,Deploy Global Paradigms,6.871430e+12,DE,Individual,29,0.26,EUR,01/01/2024,31/01/2024,746131581
1,Jacqueline Gutierrez,Dead Oceans,Digitized Optimal Core,GBVNH2445772,Expedite Synergistic Synergies,8.006070e+12,NO,Individual,2426,18.52,USD,01/01/2024,31/01/2024,153168852
2,Miller & Castaneda,"Wilkinson, Recordings",Intuitive Didactic Complexity,DEYY42341711,Re-Intermediate Value-Added E-Markets - Single,9.708640e+12,AR,Individual,19,0.08,USD,01/01/2024,31/01/2024,702745173
3,Jones & Montoya,"Martinez, Sounds",Configurable Multi-Tasking Collaboration,FRTUT2216870,Monetize One-To-One Partnerships - Single,3.488970e+12,JP,Individual,4,4.50,JPY,01/01/2024,31/01/2024,298224126
4,Sarah Mccann,Lopez Recordings,Horizontal Stable Productivity,USTDZ2372394,Engage E-Business Niches,9.724560e+12,BR,Individual,209,1.41,USD,01/01/2024,31/01/2024,405652187

In [7]:
df_apple_feb24_raw = pd.read_csv('inbound_reports/apple_feb24_raw.csv')
df_apple_feb24_raw.head()

,Artist,Label,Song_Title,ISRC,Album,UPC,Territory,Subscription_Type,Plays,Earnings,Currency_Code,Report_Start_Date,Report_End_Date,Apple_ID
0,Lil Lindsey,Pure Pick Music,Digitized Bifurcated Projection,NaN,Unleash Wireless Users - EP,4.358440e+12,AR,Individual,8,0.05,USD,01/02/2024,29/02/2024,725441363
1,Harper & Goodman,"True Guzman, Audio",Robust Leadingedge Data-Warehouse,SERBA2186976,Implement E-Business Technologies,9.586190e+12,IT,Individual,8,0.05,EUR,01/02/2024,29/02/2024,589990186
2,Christopher Turner,"Burns, Jensen and Martinez Music",Cross-Group Fault-Tolerant Artificial Intellig...,DE7E41920815,Revolutionize Rich Channels,3.745480e+12,BR,Individual,71,0.33,USD,01/02/2024,29/02/2024,194024397
3,Jennifer Leblanc,Pure Live Recordings,Focused Maximized Pricing Structure (Acoustic),SE36F2235401,Cultivate User-Centric Synergies - Single,9.463020e+12,GB,Individual,119,0.78,GBP,01/02/2024,29/02/2024,944829771
4,Clark and the Thens,!K7 Records,Multi-Channeled Heuristic Parallelism,NLNPO2456494,Evolve Cross-Platform Communities - EP,8.395050e+12,SE,Individual,1797,13.70,USD,01/02/2024,29/02/2024,647377161

In [8]:
df_apple_mar24_raw = pd.read_csv('inbound_reports/apple_mar24_raw.csv')
df_apple_mar24_raw.head()

,Artist,Label,Song_Title,ISRC,Album,UPC,Territory,Subscription_Type,Plays,Earnings,Currency_Code,Report_Start_Date,Report_End_Date,Apple_ID
0,DJ Parrish,Redeye Worldwide,Public-Key System-Worthy Encoding,NLMED1971596,Seize 24/365 Networks,2.224610e+12,GB,Individual,1380,9.84,GBP,01/03/2024,31/03/2024,577591600
1,Jenna Sanchez,"Simpson, Patel and Barajas Recordings",Extended Real-Time System Engine,SE5IO2054647,Monetize Impactful Eyeballs,3.593810e+12,AR,Individual,15,0.08,USD,01/03/2024,31/03/2024,676236740
2,Mr. William Young DDS,FUGA,Digitized System-Worthy Hardware,USKHC2432610,Extend Impactful E-Tailers,1.509320e+12,JP,Individual,166,160.50,JPY,01/03/2024,31/03/2024,803730803
3,Hines and the Decisions,Pure Walsh Audio,Pre-Emptive Asymmetric Implementation,US2XG1969418,Architect Open-Source Vortals,7.734040e+12,IN,Individual,18,0.10,USD,01/03/2024,31/03/2024,634739915
4,Jimenez & Jackson,Glass Tapes,Cross-Group Mission-Critical Conglomeration,NL7JO2368972,Whiteboard Virtual Partnerships,2.987840e+12,PL,Individual,1,0.01,USD,01/03/2024,31/03/2024,226783403

In [9]:
df_deezer_jan24_raw = pd.read_csv('inbound_reports/deezer_jan24_raw.csv')
df_deezer_jan24_raw.head()

,Artiste,Label,Titre,ISRC,Album,UPC,Pays,Type_Compte,Ecoutes,Revenus,Devise,Date_Debut,Date_Fin,Deezer_Track_ID
0,Walker and the Commons,Green PLC Records,Progressive Bi-Directional Projection,FREOV2232082,Integrate Distributed Web-Readiness,9.301136e+11,PL,Free,620,0.14,EUR,01/01/2024,31/01/2024,20225769
1,Martinez and the Teachers,Carroll-Alvarado Label,Universal System-Worthy Conglomeration (Acoustic),FR2DK1874809,E-Enable Front-End Content - EP,8.665550e+12,KR,Premium,17,0.06,EUR,01/01/2024,31/01/2024,67921552
2,The Suddenlys,Carroll-Alvarado Label,User-Centric 24/7 Hub,GBMHR2438777,Unleash Global Mindshare,9.749420e+12,JP,Premium,129,0.59,EUR,01/01/2024,31/01/2024,72365553
3,Davis and the Degrees,True Perez-Pittman Audio,Fully-Configurable Leadingedge Core (Acoustic),FRO8B2413981,Integrate Holistic Technologies,3.586430e+12,BR,Free,1,0.00,EUR,01/01/2024,31/01/2024,81629973
4,Big Turner,"Bridges, Kelley and Hanson Label",Public-Key Bandwidth-Monitored Challenge (Remix),GBX582399854,Utilize B2C E-Services,7.558225e+11,SE,Premium,9,0.06,EUR,01/01/2024,31/01/2024,41943264

In [10]:
df_deezer_feb24_raw = pd.read_csv('inbound_reports/deezer_feb24_raw.csv')
df_deezer_feb24_raw.head()

,Artiste,Label,Titre,ISRC,Album,UPC,Pays,Type_Compte,Ecoutes,Revenus,Devise,Date_Debut,Date_Fin,Deezer_Track_ID
0,Levine & Lee,Green PLC Records,NaN,NLPK72263871,Iterate Out-Of-The-Box E-Markets,3.327840e+12,BR,Premium,10,0.03,EUR,01/02/2024,29/02/2024,15122384
1,MC Olson,"Brown, Productions",Inverse Disintermediate Frame,SE8TC2313753,Grow Clicks-And-Mortar Eyeballs,9.796790e+12,IT,Premium,23,0.10,EUR,01/02/2024,29/02/2024,94073445
2,Harris & Bryan,Parker and Sons Music,Enhanced Client-Server Neural-Net,DELHE2290055,Transition Distributed Systems - EP,4.928930e+12,AU,Premium,18,0.13,EUR,01/02/2024,29/02/2024,42613226
3,Adam Wright,"Lynch, Torres and Stewart Label",Right-Sized Grid-Enabled Productivity,NL6NG2275814,Engineer Integrated Web-Readiness,5.422120e+11,CL,Premium,29,0.10,EUR,01/02/2024,29/02/2024,89313356
4,Weber & Knight,True Collins Records,Organized Even-Keeled Strategy (Radio Edit),FRNJV2215322,Repurpose Cross-Media Web-Readiness,6.747082e+11,NO,Premium,9,0.06,EUR,01/02/2024,29/02/2024,37513364

In [11]:
df_deezer_mar24_raw = pd.read_csv('inbound_reports/deezer_mar24_raw.csv')
df_deezer_mar24_raw.head()

,Artiste,Label,Titre,ISRC,Album,UPC,Pays,Type_Compte,Ecoutes,Revenus,Devise,Date_Debut,Date_Fin,Deezer_Track_ID
0,Samuel Evans,"Underground Wheeler, Recordings",Focused Object-Oriented Graphical User Interfa...,FREFN2370500,Deploy Leading-Edge Channels,4.307650e+12,FR,Premium,15,0.06,EUR,01/03/2024,31/03/2024,79444093
1,Cox and the Walks,Underground Olson Music,Sharable Holistic Workforce,FRNQK2361139,Visualize Compelling Eyeballs,3.821260e+12,IT,Premium,3,0.01,EUR,01/03/2024,31/03/2024,40675991
2,Nichols & Lin,New Walton-Evans Audio,Seamless 5Thgeneration Model (Remix),GBMQ82154356,E-Enable Turn-Key Portals,7.019540e+12,PL,Free,1,0.00,EUR,01/03/2024,31/03/2024,54527695
3,Garcia and the Notes,Idea Records,Triple-Buffered Multimedia Strategy (Radio Edit),FRGDW2464820,Scale Bleeding-Edge Deliverables - EP,8.971880e+12,IT,Premium,2,0.01,EUR,01/03/2024,31/03/2024,40361105
4,Jane Hudson,FUGA,Persistent Optimizing Algorithm (Live),DES8P1950413,Harness 24/365 Web-Readiness,5.321620e+12,CL,Premium,256,1.03,EUR,01/03/2024,31/03/2024,30003159

In [12]:
df_spotify_jan24_raw = pd.read_csv('inbound_reports/spotify_jan24_raw.csv')
df_spotify_jan24_raw.head()

,artist_name,label_name,track_title,isrc,album_title,upc,country_code,stream_type,streams,royalty_amount,currency,period_start,period_end
0,Wiggins & Ball,Warp Records,Function-Based Mobile Challenge,NLSXD1849510,Re-Contextualize Integrated Infrastructures,3.420405e+11,CA,Premium,436,2.13,USD,01/01/2024,31/01/2024
1,Lee & Chung,Harris-Greer Entertainment,Managed Foreground Hub,USMT51887504,Grow B2C Paradigms - Single,7.607030e+12,AU,Premium,621,1.93,USD,01/01/2024,31/01/2024
2,Allen Hickman,"Johnson, Harrell and Holt Music Group",Adaptive 24Hour Synergy,SE5V02042244,Evolve Open-Source Synergies,8.214640e+12,KR,Premium,373,0.73,USD,01/01/2024,31/01/2024
3,Anderson and the Companys,Bridges Group Label,Sharable Hybrid Knowledge User (Live),DE19Z2079434,Utilize Cross-Media Channels - EP,2.759210e+12,JP,Premium,43,16.50,JPY,01/01/2024,31/01/2024
4,Christopher Hamilton,Redeye Worldwide,Proactive Responsive Forecast,GB4H82295591,Unleash Robust E-Business,6.732250e+12,FR,Free,872,0.33,EUR,01/01/2024,31/01/2024

In [13]:
df_spotify_feb24_raw = pd.read_csv('inbound_reports/spotify_feb24_raw.csv')
df_spotify_feb24_raw.head()

,artist_name,label_name,track_title,isrc,album_title,upc,country_code,stream_type,streams,royalty_amount,currency,period_start,period_end
0,Hall and the Abouts,Symphonic Distribution,Front-Line Regional Service-Desk,FR59O1839718,Engineer Cross-Media Schemas - Single,2.064650e+12,JP,Premium,580,220.50,JPY,01/02/2024,29/02/2024
1,Singleton & Ballard,Polyvinyl Record Co.,Vision-Oriented 5Thgeneration Capacity (Remix),FR9FM1882596,Evolve Web-Enabled Communities,9.008470e+12,FR,Free,845,0.38,EUR,01/02/2024,29/02/2024
2,Lee and the Churchs,Symphonic Distribution,Reactive Client-Driven Project,US0QK2258798,Synthesize Open-Source E-Tailers,6.522880e+12,NL,Premium,295,1.28,EUR,01/02/2024,29/02/2024
3,Karen Ibarra,Wood Music,Fundamental Fresh-Thinking Capability (Acoustic),GB7PT2285311,Morph Leading-Edge Applications - EP,6.604370e+12,AR,Free,32,0.02,USD,01/02/2024,29/02/2024
4,Diaz & King,Montgomery Group Music,Persistent Asymmetric Capacity,FRZ172168817,Maximize Vertical Networks,9.788720e+12,CO,Premium,417,0.99,USD,01/02/2024,29/02/2024

In [14]:
df_spotify_mar24_raw = pd.read_csv('inbound_reports/spotify_mar24_raw.csv')
df_spotify_mar24_raw.head()

,artist_name,label_name,track_title,isrc,album_title,upc,country_code,stream_type,streams,royalty_amount,currency,period_start,period_end
0,Chloe Roach,Montgomery Group Music,Upgradable Context-Sensitive Leverage,FRDC52372518,Generate Visionary Interfaces,2.140480e+12,PL,Free,306,0.13,USD,01/03/2024,31/03/2024
1,Roy Martin,True Some Sounds,Business-Focused Object-Oriented Interface,DEVNP1982135,Incubate Scalable Methodologies,3.770980e+12,GB,Premium,5,0.02,GBP,01/03/2024,31/03/2024
2,Joshua Wood,Harris-Greer Entertainment,Polarized Content-Based Architecture,SEYK62268118,Morph Mission-Critical Technologies,4.325840e+12,DE,Premium,14,0.06,EUR,01/03/2024,31/03/2024
3,Daniels & Velez,Raw Parsons Sounds,Synergistic Contextually-Based Encryption,GBW9H2127704,Enable Scalable Deliverables,1.053180e+12,BR,Premium,5,0.01,USD,01/03/2024,31/03/2024
4,Clark and the Becomes,Randolph Inc Records,Digitized Mission-Critical Instruction Set,FR51P1928235,Envisioneer Seamless Relationships,1.983350e+12,ES,Free,2106,1.09,EUR,01/03/2024,31/03/2024

In [15]:
df_youtube_jan24_raw = pd.read_csv('inbound_reports/youtube_jan24_raw.csv')
df_youtube_jan24_raw.head()

,Channel_Name,Rights_Owner,Video_Title,Asset_ISRC,Album_Title,Asset_UPC,Country_of_Sale,Content_Type,Views,Estimated_Revenue,Currency,Start_Date,End_Date,Video_ID,Asset_ID
0,Luna & Bell,Moore Inc Records,Progressive Fresh-Thinking Emulation,NL9KH2153111,Mesh Innovative E-Tailers - Single,8.545080e+12,KR,Ad-Supported,40,0.01,USD,01/01/2024,31/01/2024,g9cpoM8JTqP,Z7UJXTUXOIQBANFU
1,The Majors,True Cochran Tapes,Business-Focused Dynamic Customer Loyalty,FRTGP2018816,Optimize Cross-Media Initiatives,9.444060e+12,US,Ad-Supported,31,0.02,USD,01/01/2024,31/01/2024,cX1OUggH6SO,BPVUD0CEWXVHPZ06
2,Kathryn Benson,"Brown, Recordings",Operative Exuding Focus Group,SES2Z2255756,Unleash Viral Partnerships,3.362882e+11,GB,Premium,44,0.13,GBP,01/01/2024,31/01/2024,WLukOMCeBMI,IL6GLVUPSOGKNVFC
3,Sullivan & Martinez,Red Bull Records,Quality-Focused Mission-Critical Strategy,SEF1E2218977,Architect Global Paradigms,4.280615e+11,KR,Ad-Supported,1424,0.24,USD,01/01/2024,31/01/2024,LLb-nRP387l,5OLGJH0NA9A3NRLL
4,Big Rosales,Secretly Canadian,Customizable Real-Time Benchmark,FREB51823022,Evolve Customized Infrastructures,4.876224e+11,MX,Ad-Supported,230,0.04,USD,01/01/2024,31/01/2024,og_f-JrKJPm,WKRQOW01MZA1TG2G

In [16]:
df_youtube_feb24_raw = pd.read_csv('inbound_reports/youtube_feb24_raw.csv')
df_youtube_feb24_raw.head()

,Channel_Name,Rights_Owner,Video_Title,Asset_ISRC,Album_Title,Asset_UPC,Country_of_Sale,Content_Type,Views,Estimated_Revenue,Currency,Start_Date,End_Date,Video_ID,Asset_ID
0,Escobar & Franklin,Secretly Canadian,Cross-Platform Dynamic Workforce (Radio Edit),GBZJC2215364,Iterate Compelling Web-Readiness - EP,2.941310e+12,NO,Ad-Supported,791,0.41,USD,01/02/2024,29/02/2024,TFfpFO-yt8u,WJO6KV81PU38P8K2
1,Sutton and the Investments,FUGA,Phased Secondary Task-Force,DEKNT1914787,Morph Clicks-And-Mortar Channels,5.006580e+12,MX,Ad-Supported,1834,0.68,USD,01/02/2024,29/02/2024,2Oc-DHJU8mt,XEVT5NK3BQQRQTMH
2,Murphy & Russell,"Salas, Williamson and Wallace Label",Balanced Zero Tolerance Groupware,US4Q81877453,Iterate B2C E-Services - Single,7.805680e+12,SE,Ad-Supported,5938,4.41,USD,01/02/2024,29/02/2024,nrsnpOwcQtW,4XK61IP2YI4YQG5L
3,Jacqueline Ramos,!K7 Records,Assimilated Context-Sensitive Capability,GBGH62024733,Engage Web-Enabled Action-Items - Single,6.043590e+12,US,Ad-Supported,200,0.08,USD,01/02/2024,29/02/2024,1vnh-7GwqU-,TZCIMTKFAHB49R8A
4,Wallace & Davis,Raw Johnson Sounds,Persevering Hybrid Matrix,SEYP61916035,Harness Frictionless Deliverables,6.585770e+12,ES,Ad-Supported,297,0.08,EUR,01/02/2024,29/02/2024,c--6aQYEMxq,016JD7VVHM9TXNC5

In [17]:
df_youtube_mar24_raw = pd.read_csv('inbound_reports/youtube_mar24_raw.csv')
df_youtube_mar24_raw.head()

,Channel_Name,Rights_Owner,Video_Title,Asset_ISRC,Album_Title,Asset_UPC,Country_of_Sale,Content_Type,Views,Estimated_Revenue,Currency,Start_Date,End_Date,Video_ID,Asset_ID
0,Big Kaufman,Raw Art Recordings,Focused Regional Middleware,GBKH01915309,Whiteboard Dot-Com Synergies,5.202790e+12,US,Ad-Supported,10,0.01,USD,01/03/2024,31/03/2024,zHaW3fxxvQX,5ZDGOFZW9D2X17F2
1,Hensley and the Specials,Singh Music,Reactive Client-Driven Flexibility,SEXXV1847606,Visualize End-To-End Methodologies,6.078590e+12,AU,Premium,21,0.07,USD,01/03/2024,31/03/2024,eWr4ur2sujX,QOCA8XINNCYWW5LB
2,Stewart and the Untils,Anti-,Realigned Executive Forecast,FRRAD2456733,Facilitate One-To-One Web Services - Single,2.225960e+12,NO,Ad-Supported,717,0.43,USD,01/03/2024,31/03/2024,jllXF-yYgY4,YX5WYFK7XTU59GLQ
3,Montgomery & Hampton,Underground Often Records,Compatible Local Array,SEIVK2261904,Aggregate Collaborative Channels - Single,2.808240e+12,DE,Premium,6,0.02,EUR,01/03/2024,31/03/2024,G8fGW7kg5I9,KW4CXQXGPASMHB8Y
4,Big Perkins,Main Tapes,Vision-Oriented Actuating Database,FRIBT2224778,Whiteboard Clicks-And-Mortar Vortals,1.093560e+12,SE,Ad-Supported,156,0.12,USD,01/03/2024,31/03/2024,tkPRPac9uhj,CILF64PKQ6O0BG23

---

## csv dfs check

In [18]:

df_amazon_jan24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ArtistName    150000 non-null  str
 1   LabelName     149998 non-null  str
 2   TrackTitle    150000 non-null  str
 3   ISRC          149996 non-null  str
 4   AlbumTitle    150000 non-null  str
 5   UPC           150000 non-null  float64
 6   CountryCode   150000 non-null  str
 7   Service_Tier  150000 non-null  str
 8   PlayCount     150000 non-null  int64
 9   Royalty       150000 non-null  float64
 10  CurrencyCode  150000 non-null  str
 11  Period_Start  150000 non-null  str
 12  Period_End    150000 non-null  str
 13  ASIN          150000 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 38.5 MB

- 4 'ISRC' null
- 2 'LabelName' null

In [19]:
df_amazon_feb24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ArtistName    150000 non-null  str
 1   LabelName     150000 non-null  str
 2   TrackTitle    150000 non-null  str
 3   ISRC          150000 non-null  str
 4   AlbumTitle    150000 non-null  str
 5   UPC           150000 non-null  float64
 6   CountryCode   150000 non-null  str
 7   Service_Tier  150000 non-null  str
 8   PlayCount     150000 non-null  int64
 9   Royalty       150000 non-null  float64
 10  CurrencyCode  150000 non-null  str
 11  Period_Start  150000 non-null  str
 12  Period_End    150000 non-null  str
 13  ASIN          150000 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 38.4 MB

In [20]:
df_amazon_mar24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ArtistName    150000 non-null  str
 1   LabelName     150000 non-null  str
 2   TrackTitle    149997 non-null  str
 3   ISRC          150000 non-null  str
 4   AlbumTitle    150000 non-null  str
 5   UPC           150000 non-null  float64
 6   CountryCode   150000 non-null  str
 7   Service_Tier  150000 non-null  str
 8   PlayCount     150000 non-null  int64
 9   Royalty       150000 non-null  float64
 10  CurrencyCode  150000 non-null  str
 11  Period_Start  150000 non-null  str
 12  Period_End    150000 non-null  str
 13  ASIN          150000 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 38.5 MB

- 3 'TrackTitle' null

In [21]:
df_apple_jan24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 14 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Artist             150000 non-null  str
 1   Label              150000 non-null  str
 2   Song_Title         150000 non-null  str
 3   ISRC               150000 non-null  str
 4   Album              150000 non-null  str
 5   UPC                150000 non-null  float64
 6   Territory          150000 non-null  str
 7   Subscription_Type  150000 non-null  str
 8   Plays              150000 non-null  int64
 9   Earnings           150000 non-null  float64
 10  Currency_Code      150000 non-null  str
 11  Report_Start_Date  150000 non-null  str
 12  Report_End_Date    150000 non-null  str
 13  Apple_ID           150000 non-null  int64
dtypes: float64(2), int64(2), str(10)
memory usage: 37.4 MB

In [22]:
df_apple_feb24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 14 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Artist             150000 non-null  str
 1   Label              149996 non-null  str
 2   Song_Title         149986 non-null  str
 3   ISRC               149983 non-null  str
 4   Album              149999 non-null  str
 5   UPC                150000 non-null  float64
 6   Territory          150000 non-null  str
 7   Subscription_Type  150000 non-null  str
 8   Plays              150000 non-null  int64
 9   Earnings           150000 non-null  float64
 10  Currency_Code      150000 non-null  str
 11  Report_Start_Date  150000 non-null  str
 12  Report_End_Date    150000 non-null  str
 13  Apple_ID           150000 non-null  int64
dtypes: float64(2), int64(2), str(10)
memory usage: 37.5 MB

- 4 'Label' null
- 12 'Song_Title' null
- 17 'ISRC' null
- 1 'Album' null

In [23]:
df_apple_mar24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 14 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Artist             149999 non-null  str
 1   Label              149994 non-null  str
 2   Song_Title         149996 non-null  str
 3   ISRC               149996 non-null  str
 4   Album              150000 non-null  str
 5   UPC                150000 non-null  float64
 6   Territory          150000 non-null  str
 7   Subscription_Type  150000 non-null  str
 8   Plays              150000 non-null  int64
 9   Earnings           150000 non-null  float64
 10  Currency_Code      150000 non-null  str
 11  Report_Start_Date  150000 non-null  str
 12  Report_End_Date    150000 non-null  str
 13  Apple_ID           150000 non-null  int64
dtypes: float64(2), int64(2), str(10)
memory usage: 37.5 MB

- 1 'Artist' null
- 4 'Label' null
- 4 'Song_Title' null
- 4 'ISRC' null

In [24]:
df_deezer_jan24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Artiste          149998 non-null  str
 1   Label            149997 non-null  str
 2   Titre            149998 non-null  str
 3   ISRC             150000 non-null  str
 4   Album            149998 non-null  str
 5   UPC              149999 non-null  float64
 6   Pays             150000 non-null  str
 7   Type_Compte      150000 non-null  str
 8   Ecoutes          150000 non-null  int64
 9   Revenus          150000 non-null  float64
 10  Devise           150000 non-null  str
 11  Date_Debut       150000 non-null  str
 12  Date_Fin         150000 non-null  str
 13  Deezer_Track_ID  150000 non-null  int64
dtypes: float64(2), int64(2), str(10)
memory usage: 36.9 MB

- 2 'Artiste' null
- 3 'Label' null
- 2 'Titre' null
- 2 'Album' null
- 1 'UPC' null

In [25]:
df_deezer_feb24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Artiste          149996 non-null  str
 1   Label            149994 non-null  str
 2   Titre            149998 non-null  str
 3   ISRC             149996 non-null  str
 4   Album            149998 non-null  str
 5   UPC              149999 non-null  float64
 6   Pays             150000 non-null  str
 7   Type_Compte      150000 non-null  str
 8   Ecoutes          150000 non-null  int64
 9   Revenus          150000 non-null  float64
 10  Devise           150000 non-null  str
 11  Date_Debut       150000 non-null  str
 12  Date_Fin         150000 non-null  str
 13  Deezer_Track_ID  150000 non-null  int64
dtypes: float64(2), int64(2), str(10)
memory usage: 36.9 MB

- 4 Artiste null
- 6 Label null
- 2 Titre null
- 4 ISRC null
- 2 Album null
- 1 UPC null

In [26]:
df_deezer_mar24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Artiste          149999 non-null  str
 1   Label            150000 non-null  str
 2   Titre            149999 non-null  str
 3   ISRC             149998 non-null  str
 4   Album            150000 non-null  str
 5   UPC              150000 non-null  float64
 6   Pays             150000 non-null  str
 7   Type_Compte      150000 non-null  str
 8   Ecoutes          150000 non-null  int64
 9   Revenus          150000 non-null  float64
 10  Devise           150000 non-null  str
 11  Date_Debut       150000 non-null  str
 12  Date_Fin         150000 non-null  str
 13  Deezer_Track_ID  150000 non-null  int64
dtypes: float64(2), int64(2), str(10)
memory usage: 36.9 MB

- 1 Artiste null
- 1 Titre null
- 2 ISRC null

In [27]:
df_spotify_jan24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   artist_name     149994 non-null  str
 1   label_name      149995 non-null  str
 2   track_title     149997 non-null  str
 3   isrc            149996 non-null  str
 4   album_title     149999 non-null  str
 5   upc             150000 non-null  float64
 6   country_code    150000 non-null  str
 7   stream_type     150000 non-null  str
 8   streams         150000 non-null  int64
 9   royalty_amount  150000 non-null  float64
 10  currency        150000 non-null  str
 11  period_start    150000 non-null  str
 12  period_end      150000 non-null  str
dtypes: float64(2), int64(1), str(10)
memory usage: 35.8 MB

- 6 artist_name null
- 5 label_name null
- 3 track_title null
- 4 isrc null
- 1 album_title null

In [28]:
df_spotify_feb24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   artist_name     149996 non-null  str
 1   label_name      149998 non-null  str
 2   track_title     149997 non-null  str
 3   isrc            149998 non-null  str
 4   album_title     149996 non-null  str
 5   upc             150000 non-null  float64
 6   country_code    150000 non-null  str
 7   stream_type     150000 non-null  str
 8   streams         150000 non-null  int64
 9   royalty_amount  150000 non-null  float64
 10  currency        150000 non-null  str
 11  period_start    150000 non-null  str
 12  period_end      150000 non-null  str
dtypes: float64(2), int64(1), str(10)
memory usage: 35.8 MB

- 4 artist_name null
- 2 label_name null
- 3 track_title null
- 2 isrc null
- 4 album_title null

In [29]:
df_spotify_mar24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   artist_name     149996 non-null  str
 1   label_name      149995 non-null  str
 2   track_title     149996 non-null  str
 3   isrc            150000 non-null  str
 4   album_title     149998 non-null  str
 5   upc             150000 non-null  float64
 6   country_code    150000 non-null  str
 7   stream_type     150000 non-null  str
 8   streams         150000 non-null  int64
 9   royalty_amount  150000 non-null  float64
 10  currency        150000 non-null  str
 11  period_start    150000 non-null  str
 12  period_end      150000 non-null  str
dtypes: float64(2), int64(1), str(10)
memory usage: 35.7 MB

- 4 artist_name null
- 5 label_name null
- 6 track_title null
- 2 album_title null

In [30]:
df_youtube_jan24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Channel_Name       149997 non-null  str
 1   Rights_Owner       150000 non-null  str
 2   Video_Title        149997 non-null  str
 3   Asset_ISRC         149999 non-null  str
 4   Album_Title        149997 non-null  str
 5   Asset_UPC          149997 non-null  float64
 6   Country_of_Sale    150000 non-null  str
 7   Content_Type       150000 non-null  str
 8   Views              150000 non-null  int64
 9   Estimated_Revenue  150000 non-null  float64
 10  Currency           150000 non-null  str
 11  Start_Date         150000 non-null  str
 12  End_Date           150000 non-null  str
 13  Video_ID           150000 non-null  str
 14  Asset_ID           150000 non-null  str
dtypes: float64(2), int64(1), str(12)
memory usage: 42.4 MB

- 3 Channel_Name null
- 3 Video_Title null
- 1 Asset_ISRC null
- 3 Album_Title null
- 3 Asset_UPC null

In [31]:
df_youtube_feb24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Channel_Name       149992 non-null  str
 1   Rights_Owner       149997 non-null  str
 2   Video_Title        149996 non-null  str
 3   Asset_ISRC         149999 non-null  str
 4   Album_Title        149998 non-null  str
 5   Asset_UPC          149998 non-null  float64
 6   Country_of_Sale    150000 non-null  str
 7   Content_Type       150000 non-null  str
 8   Views              150000 non-null  int64
 9   Estimated_Revenue  150000 non-null  float64
 10  Currency           150000 non-null  str
 11  Start_Date         150000 non-null  str
 12  End_Date           150000 non-null  str
 13  Video_ID           150000 non-null  str
 14  Asset_ID           150000 non-null  str
dtypes: float64(2), int64(1), str(12)
memory usage: 42.4 MB

- 8 'Channel_Name' null
- 3 'Rights_Owner' null
- 4 'Video_Title null
- 1 'Asset_ISRC' null
- 2 'Album_Title' null
- 2 'Asset_UPC' null

In [32]:
df_youtube_mar24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Channel_Name       149996 non-null  str
 1   Rights_Owner       149998 non-null  str
 2   Video_Title        150000 non-null  str
 3   Asset_ISRC         149998 non-null  str
 4   Album_Title        149997 non-null  str
 5   Asset_UPC          150000 non-null  float64
 6   Country_of_Sale    150000 non-null  str
 7   Content_Type       150000 non-null  str
 8   Views              150000 non-null  int64
 9   Estimated_Revenue  150000 non-null  float64
 10  Currency           150000 non-null  str
 11  Start_Date         150000 non-null  str
 12  End_Date           150000 non-null  str
 13  Video_ID           150000 non-null  str
 14  Asset_ID           150000 non-null  str
dtypes: float64(2), int64(1), str(12)
memory usage: 42.4 MB

- 4 'Channel_Name' null
- 2 'Rights_Owner' null
- 2 'Asset_ISRC' null
- 3 'Album_Title' null

## Data cleaning

### df_amazon_jan24_raw

In [ ]:

df_amazon_jan24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ArtistName    150000 non-null  str
 1   LabelName     149998 non-null  str
 2   TrackTitle    150000 non-null  str
 3   ISRC          149996 non-null  str
 4   AlbumTitle    150000 non-null  str
 5   UPC           150000 non-null  float64
 6   CountryCode   150000 non-null  str
 7   Service_Tier  150000 non-null  str
 8   PlayCount     150000 non-null  int64
 9   Royalty       150000 non-null  float64
 10  CurrencyCode  150000 non-null  str
 11  Period_Start  150000 non-null  str
 12  Period_End    150000 non-null  str
 13  ASIN          150000 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 38.5 MB

In [28]:
null_counts = df_amazon_jan24_raw.isna().sum()
print('null values count:')
print(null_counts[null_counts > 0])

null values count:
LabelName    2
ISRC         4
dtype: int64

In [40]:
# Remove duplicates.
df = df_amazon_jan24_raw.drop_duplicates()

# Drop columns not required in the final schema.
df = df.drop(columns=["ASIN"])

# Cast to string and strip whitespace.
for col in ["ArtistName", "LabelName", "TrackTitle", "ISRC", "AlbumTitle", "CountryCode", "Service_Tier", "CurrencyCode"]:
    df[col] = df[col].astype("string").str.strip()

# DSP and Source columns creation.
df["DSP"] = "Amazon"
df["Source_File"] = "amazon_jan24_raw.csv"

#-----------------------------------------------------------------------------
# Fill missing LabelName using dim_track as a lookup.
isrc_to_label = (
    df_dim_track[["ISRC", "Label"]]
    .assign(ISRC=lambda x: x["ISRC"].astype("string"))
    .set_index("ISRC")["Label"]
)

# Fill missing LabelName using the lookup.
df["LabelName"] = df["LabelName"].fillna(df["ISRC"].map(isrc_to_label))

#---------
# Build a (ArtistName, TrackTitle) to ISRC lookup from dim_track.
# Lowercased on both sides to ensure the matching with the raw data.
artist_track_to_isrc = (
    df_dim_track[["Artist", "Track", "ISRC"]]
    .assign(
        Artist=lambda x: x["Artist"].astype("string").str.lower(),
        Track=lambda x: x["Track"].astype("string").str.lower(),
        ISRC=lambda x: x["ISRC"].astype("string"),
    )
    .set_index(["Artist", "Track"])["ISRC"]
    .to_dict()
)

# Fill missing ISRCs using the lookup.
df["ISRC"] = df["ISRC"].fillna(
    df.apply(lambda row: artist_track_to_isrc.get(
        (row["ArtistName"].lower(), row["TrackTitle"].lower())
    ), axis=1)
)

#-----------------------------------------------------------------------------

# Fix remaining dtypes.
df["DSP"] = df["DSP"].astype("string")
df["Source_File"] = df["Source_File"].astype("string")
df["UPC"] = df["UPC"].astype("Int64").astype("string") #.astype("Int64") to remove the decimal

# Convert dates to datetime.
df["Period_Start"] = pd.to_datetime(df["Period_Start"], dayfirst=True).dt.normalize()
df["Period_End"] = pd.to_datetime(df["Period_End"], dayfirst=True).dt.normalize()

df_amazon_jan24_clean = df
df_amazon_jan24_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ArtistName    150000 non-null  string
 1   LabelName     150000 non-null  string
 2   TrackTitle    150000 non-null  string
 3   ISRC          150000 non-null  string
 4   AlbumTitle    150000 non-null  string
 5   UPC           150000 non-null  string
 6   CountryCode   150000 non-null  string
 7   Service_Tier  150000 non-null  string
 8   PlayCount     150000 non-null  int64
 9   Royalty       150000 non-null  float64
 10  CurrencyCode  150000 non-null  string
 11  Period_Start  150000 non-null  datetime64[us]
 12  Period_End    150000 non-null  datetime64[us]
 13  DSP           150000 non-null  string
 14  Source_File   150000 non-null  string
dtypes: datetime64[us](2), float64(1), int64(1), string(11)
memory usage: 41.0 MB

Now let's copy and paste the same process to automate some tasks, but first check schema, dtypes, and null values for each DSP before applying the cleaning pipeline

### df_amazon_feb24_raw

In [ ]:
df_amazon_feb24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ArtistName    150000 non-null  str
 1   LabelName     150000 non-null  str
 2   TrackTitle    150000 non-null  str
 3   ISRC          150000 non-null  str
 4   AlbumTitle    150000 non-null  str
 5   UPC           150000 non-null  float64
 6   CountryCode   150000 non-null  str
 7   Service_Tier  150000 non-null  str
 8   PlayCount     150000 non-null  int64
 9   Royalty       150000 non-null  float64
 10  CurrencyCode  150000 non-null  str
 11  Period_Start  150000 non-null  str
 12  Period_End    150000 non-null  str
 13  ASIN          150000 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 38.4 MB

In [29]:
null_counts = df_amazon_feb24_raw.isna().sum()
print('null values count:')
print(null_counts[null_counts > 0])

null values count:
Series([], dtype: int64)

In [42]:
# Remove duplicates.
df = df_amazon_feb24_raw.drop_duplicates()

# Drop columns not required in the final schema.
df = df.drop(columns=["ASIN"])

# Cast to string and strip whitespace.
for col in ["ArtistName", "LabelName", "TrackTitle", "ISRC", "AlbumTitle", "CountryCode", "Service_Tier", "CurrencyCode"]:
    df[col] = df[col].astype("string").str.strip()

# DSP and Source columns creation.
df["DSP"] = "Amazon"
df["Source_File"] = "amazon_feb24_raw.csv"

# Fix remaining dtypes.
df["DSP"] = df["DSP"].astype("string")
df["Source_File"] = df["Source_File"].astype("string")
df["UPC"] = df["UPC"].astype("Int64").astype("string") #.astype("Int64") to remove the decimal

# Convert dates to datetime.
df["Period_Start"] = pd.to_datetime(df["Period_Start"], dayfirst=True).dt.normalize()
df["Period_End"] = pd.to_datetime(df["Period_End"], dayfirst=True).dt.normalize()

df_amazon_feb24_clean = df
df_amazon_feb24_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ArtistName    150000 non-null  string
 1   LabelName     150000 non-null  string
 2   TrackTitle    150000 non-null  string
 3   ISRC          150000 non-null  string
 4   AlbumTitle    150000 non-null  string
 5   UPC           150000 non-null  string
 6   CountryCode   150000 non-null  string
 7   Service_Tier  150000 non-null  string
 8   PlayCount     150000 non-null  int64
 9   Royalty       150000 non-null  float64
 10  CurrencyCode  150000 non-null  string
 11  Period_Start  150000 non-null  datetime64[us]
 12  Period_End    150000 non-null  datetime64[us]
 13  DSP           150000 non-null  string
 14  Source_File   150000 non-null  string
dtypes: datetime64[us](2), float64(1), int64(1), string(11)
memory usage: 41.0 MB

### df_amazon_mar24_raw

In [ ]:
df_amazon_mar24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ArtistName    150000 non-null  str
 1   LabelName     150000 non-null  str
 2   TrackTitle    149997 non-null  str
 3   ISRC          150000 non-null  str
 4   AlbumTitle    150000 non-null  str
 5   UPC           150000 non-null  float64
 6   CountryCode   150000 non-null  str
 7   Service_Tier  150000 non-null  str
 8   PlayCount     150000 non-null  int64
 9   Royalty       150000 non-null  float64
 10  CurrencyCode  150000 non-null  str
 11  Period_Start  150000 non-null  str
 12  Period_End    150000 non-null  str
 13  ASIN          150000 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 38.5 MB

In [33]:
null_counts = df_amazon_mar24_raw.isna().sum()
print('null values count:')
print(null_counts[null_counts > 0])

null values count:
TrackTitle    3
dtype: int64

In [47]:
# Remove duplicates.
df = df_amazon_mar24_raw.drop_duplicates()

# Drop columns not required in the final schema.
df = df.drop(columns=["ASIN"])

# Cast to string and strip whitespace.
for col in ["ArtistName", "LabelName", "TrackTitle", "ISRC", "AlbumTitle", "CountryCode", "Service_Tier", "CurrencyCode"]:
    df[col] = df[col].astype("string").str.strip()

# DSP and Source columns creation.
df["DSP"] = "Amazon"
df["Source_File"] = "amazon_mar24_raw.csv"

#-----------------------------------------------------------------------------
# Fill missing TrackTitle using dim_track as a lookup.
isrc_to_tracktitle = (
    df_dim_track[["ISRC", "Track"]]
    .assign(ISRC=lambda x: x["ISRC"].astype("string"))
    .set_index("ISRC")["Track"]
)

# Fill missing TrackTitle using the lookup.
df["TrackTitle"] = df["TrackTitle"].fillna(df["ISRC"].map(isrc_to_tracktitle))

#-----------------------------------------------------------------------------
# Fix remaining dtypes.
df["DSP"] = df["DSP"].astype("string")
df["Source_File"] = df["Source_File"].astype("string")
df["UPC"] = df["UPC"].astype("Int64").astype("string") #.astype("Int64") to remove the decimal

# Convert dates to datetime.
df["Period_Start"] = pd.to_datetime(df["Period_Start"], dayfirst=True).dt.normalize()
df["Period_End"] = pd.to_datetime(df["Period_End"], dayfirst=True).dt.normalize()

df_amazon_mar24_clean = df
df_amazon_mar24_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ArtistName    150000 non-null  string
 1   LabelName     150000 non-null  string
 2   TrackTitle    150000 non-null  string
 3   ISRC          150000 non-null  string
 4   AlbumTitle    150000 non-null  string
 5   UPC           150000 non-null  string
 6   CountryCode   150000 non-null  string
 7   Service_Tier  150000 non-null  string
 8   PlayCount     150000 non-null  int64
 9   Royalty       150000 non-null  float64
 10  CurrencyCode  150000 non-null  string
 11  Period_Start  150000 non-null  datetime64[us]
 12  Period_End    150000 non-null  datetime64[us]
 13  DSP           150000 non-null  string
 14  Source_File   150000 non-null  string
dtypes: datetime64[us](2), float64(1), int64(1), string(11)
memory usage: 41.0 MB

### df_apple_jan24_raw

In [ ]:
df_apple_jan24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 14 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Artist             150000 non-null  str
 1   Label              150000 non-null  str
 2   Song_Title         150000 non-null  str
 3   ISRC               150000 non-null  str
 4   Album              150000 non-null  str
 5   UPC                150000 non-null  float64
 6   Territory          150000 non-null  str
 7   Subscription_Type  150000 non-null  str
 8   Plays              150000 non-null  int64
 9   Earnings           150000 non-null  float64
 10  Currency_Code      150000 non-null  str
 11  Report_Start_Date  150000 non-null  str
 12  Report_End_Date    150000 non-null  str
 13  Apple_ID           150000 non-null  int64
dtypes: float64(2), int64(2), str(10)
memory usage: 37.4 MB

In [32]:
null_counts = df_apple_jan24_raw.isna().sum()
print('null values count:')
print(null_counts[null_counts > 0])

null values count:
Series([], dtype: int64)

In [51]:
# Remove duplicates.
df = df_apple_jan24_raw.drop_duplicates()

# Drop columns not required in the final schema.
df = df.drop(columns=["Apple_ID"])

# Cast to string and strip whitespace.
for col in ["Artist", "Label", "Song_Title", "ISRC", "Album", "Territory", "Subscription_Type", "Currency_Code"]:
    df[col] = df[col].astype("string").str.strip()

# DSP and Source columns creation.
df["DSP"] = "apple"
df["Source_File"] = "apple_jan24_raw.csv"

# Fix remaining dtypes.
df["DSP"] = df["DSP"].astype("string")
df["Source_File"] = df["Source_File"].astype("string")
df["UPC"] = df["UPC"].astype("Int64").astype("string") #.astype("Int64") to remove the decimal

# Convert dates to datetime.
df["Report_Start_Date"] = pd.to_datetime(df["Report_Start_Date"], dayfirst=True).dt.normalize()
df["Report_End_Date"] = pd.to_datetime(df["Report_End_Date"], dayfirst=True).dt.normalize()

df_apple_jan24_clean = df
df_apple_jan24_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Artist             150000 non-null  string
 1   Label              150000 non-null  string
 2   Song_Title         150000 non-null  string
 3   ISRC               150000 non-null  string
 4   Album              150000 non-null  string
 5   UPC                150000 non-null  string
 6   Territory          150000 non-null  string
 7   Subscription_Type  150000 non-null  string
 8   Plays              150000 non-null  int64
 9   Earnings           150000 non-null  float64
 10  Currency_Code      150000 non-null  string
 11  Report_Start_Date  150000 non-null  datetime64[us]
 12  Report_End_Date    150000 non-null  datetime64[us]
 13  DSP                150000 non-null  string
 14  Source_File        150000 non-null  string
dtypes: datetime64[us](2), float64(1), int64(1), string(11)
memory usage: 41.1 MB

### df_apple_feb24_raw

In [ ]:
df_apple_feb24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 14 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Artist             150000 non-null  str
 1   Label              149996 non-null  str
 2   Song_Title         149986 non-null  str
 3   ISRC               149983 non-null  str
 4   Album              149999 non-null  str
 5   UPC                150000 non-null  float64
 6   Territory          150000 non-null  str
 7   Subscription_Type  150000 non-null  str
 8   Plays              150000 non-null  int64
 9   Earnings           150000 non-null  float64
 10  Currency_Code      150000 non-null  str
 11  Report_Start_Date  150000 non-null  str
 12  Report_End_Date    150000 non-null  str
 13  Apple_ID           150000 non-null  int64
dtypes: float64(2), int64(2), str(10)
memory usage: 37.5 MB

In [34]:
null_counts = df_apple_feb24_raw.isna().sum()
print('null values count:')
print(null_counts[null_counts > 0])

null values count:
Label          4
Song_Title    14
ISRC          17
Album          1
dtype: int64

In [60]:
# Remove duplicates.
df = df_apple_feb24_raw.drop_duplicates()

# Drop columns not required in the final schema.
df = df.drop(columns=["Apple_ID"])

# Cast to string and strip whitespace.
for col in ["Artist", "Label", "Song_Title", "ISRC", "Album", "Territory", "Subscription_Type", "Currency_Code"]:
    df[col] = df[col].astype("string").str.strip()

# DSP and Source columns creation.
df["DSP"] = "apple"
df["Source_File"] = "apple_feb24_raw.csv"

#-----------------------------------------------------------------------------
# Fill missing Label using dim_track as a lookup.
isrc_to_label = (
    df_dim_track[["ISRC", "Label"]]
    .assign(ISRC=lambda x: x["ISRC"].astype("string"))
    .set_index("ISRC")["Label"]
)

# Fill missing Label using the lookup.
df["Label"] = df["Label"].fillna(df["ISRC"].map(isrc_to_label))

#---------
# Build a (Artist, Song_Title) to ISRC lookup from dim_track.
# Lowercased on both sides to ensure the matching with the raw data.
artist_track_to_isrc = (
    df_dim_track[["Artist", "Track", "ISRC"]]
    .assign(
        Artist=lambda x: x["Artist"].astype("string").str.lower(),
        Track=lambda x: x["Track"].astype("string").str.lower(),
        ISRC=lambda x: x["ISRC"].astype("string"),
    )
    .set_index(["Artist", "Track"])["ISRC"]
    .to_dict()
)

# Fill missing ISRCs using the lookup.
df["ISRC"] = df["ISRC"].fillna(
    df.apply(lambda row: artist_track_to_isrc.get((
        row["Artist"].lower() if pd.notna(row["Artist"]) else "",
        row["Song_Title"].lower() if pd.notna(row["Song_Title"]) else "",
    )), axis=1)
)

#---------

# Fill missing Song_Title using dim_track as a lookup.
isrc_to_songtitle = (
    df_dim_track[["ISRC", "Track"]]
    .assign(ISRC=lambda x: x["ISRC"].astype("string"))
    .set_index("ISRC")["Track"]
)
# Fill missing Song_Title using the lookup.
df["Song_Title"] = df["Song_Title"].fillna(df["ISRC"].map(isrc_to_songtitle))


#---------

# Fill missing Album using dim_track as a lookup.
isrc_to_album = (
    df_dim_track[["ISRC", "Album"]]
    .assign(ISRC=lambda x: x["ISRC"].astype("string"))
    .set_index("ISRC")["Album"]
)

# Fill missing Album using the lookup.
df["Album"] = df["Album"].fillna(df["ISRC"].map(isrc_to_album))
#-----------------------------------------------------------------------------


# Fix remaining dtypes.
df["DSP"] = df["DSP"].astype("string")
df["Source_File"] = df["Source_File"].astype("string")
df["UPC"] = df["UPC"].astype("Int64").astype("string") #.astype("Int64") to remove the decimal

# Convert dates to datetime.
df["Report_Start_Date"] = pd.to_datetime(df["Report_Start_Date"], dayfirst=True).dt.normalize()
df["Report_End_Date"] = pd.to_datetime(df["Report_End_Date"], dayfirst=True).dt.normalize()

df_apple_feb24_clean = df
df_apple_feb24_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Artist             150000 non-null  string
 1   Label              150000 non-null  string
 2   Song_Title         150000 non-null  string
 3   ISRC               150000 non-null  string
 4   Album              150000 non-null  string
 5   UPC                150000 non-null  string
 6   Territory          150000 non-null  string
 7   Subscription_Type  150000 non-null  string
 8   Plays              150000 non-null  int64
 9   Earnings           150000 non-null  float64
 10  Currency_Code      150000 non-null  string
 11  Report_Start_Date  150000 non-null  datetime64[us]
 12  Report_End_Date    150000 non-null  datetime64[us]
 13  DSP                150000 non-null  string
 14  Source_File        150000 non-null  string
dtypes: datetime64[us](2), float64(1), int64(1), string(11)
memory usage: 41.1 MB

### df_apple_mar24_raw

In [18]:
df_apple_mar24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 14 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Artist             149999 non-null  str
 1   Label              149994 non-null  str
 2   Song_Title         149996 non-null  str
 3   ISRC               149996 non-null  str
 4   Album              150000 non-null  str
 5   UPC                150000 non-null  float64
 6   Territory          150000 non-null  str
 7   Subscription_Type  150000 non-null  str
 8   Plays              150000 non-null  int64
 9   Earnings           150000 non-null  float64
 10  Currency_Code      150000 non-null  str
 11  Report_Start_Date  150000 non-null  str
 12  Report_End_Date    150000 non-null  str
 13  Apple_ID           150000 non-null  int64
dtypes: float64(2), int64(2), str(10)
memory usage: 37.5 MB

In [35]:
null_counts = df_apple_mar24_raw.isna().sum()
print('null values count:')
print(null_counts[null_counts > 0])

null values count:
Artist        1
Label         6
Song_Title    4
ISRC          4
dtype: int64

In [64]:
# Remove duplicates.
df = df_apple_mar24_raw.drop_duplicates()

# Drop columns not required in the final schema.
df = df.drop(columns=["Apple_ID"])

# Cast to string and strip whitespace.
for col in ["Artist", "Label", "Song_Title", "ISRC", "Album", "Territory", "Subscription_Type", "Currency_Code"]:
    df[col] = df[col].astype("string").str.strip()

# DSP and Source columns creation.
df["DSP"] = "apple"
df["Source_File"] = "apple_mar24_raw.csv"

#-----------------------------------------------------------------------------
# Fill missing Label using dim_track as a lookup.
isrc_to_label = (
    df_dim_track[["ISRC", "Label"]]
    .assign(ISRC=lambda x: x["ISRC"].astype("string"))
    .set_index("ISRC")["Label"]
)

# Fill missing Label using the lookup.
df["Label"] = df["Label"].fillna(df["ISRC"].map(isrc_to_label))

#---------
# Build a (Artist, Song_Title) to ISRC lookup from dim_track.
# Lowercased on both sides to ensure the matching with the raw data.
artist_track_to_isrc = (
    df_dim_track[["Artist", "Track", "ISRC"]]
    .assign(
        Artist=lambda x: x["Artist"].astype("string").str.lower(),
        Track=lambda x: x["Track"].astype("string").str.lower(),
        ISRC=lambda x: x["ISRC"].astype("string"),
    )
    .set_index(["Artist", "Track"])["ISRC"]
    .to_dict()
)

# Fill missing ISRCs using the lookup.
df["ISRC"] = df["ISRC"].fillna(
    df.apply(lambda row: artist_track_to_isrc.get((
        row["Artist"].lower() if pd.notna(row["Artist"]) else "",
        row["Song_Title"].lower() if pd.notna(row["Song_Title"]) else "",
    )), axis=1)
)

#---------

# Fill missing Song_Title using dim_track as a lookup.
isrc_to_songtitle = (
    df_dim_track[["ISRC", "Track"]]
    .assign(ISRC=lambda x: x["ISRC"].astype("string"))
    .set_index("ISRC")["Track"]
)
# Fill missing Song_Title using the lookup.
df["Song_Title"] = df["Song_Title"].fillna(df["ISRC"].map(isrc_to_songtitle))


#---------

# Fill missing Album using dim_track as a lookup.
isrc_to_album = (
    df_dim_track[["ISRC", "Album"]]
    .assign(ISRC=lambda x: x["ISRC"].astype("string"))
    .set_index("ISRC")["Album"]
)

# Fill missing Album using the lookup.
df["Album"] = df["Album"].fillna(df["ISRC"].map(isrc_to_album))

#---------

# Fill missing Artist using dim_track as a lookup.
isrc_to_artist = (
    df_dim_track[["ISRC", "Artist"]]
    .assign(ISRC=lambda x: x["ISRC"].astype("string"))
    .set_index("ISRC")["Artist"]
)

# Fill missing Artist using the lookup.
df["Artist"] = df["Artist"].fillna(df["ISRC"].map(isrc_to_artist))
#-----------------------------------------------------------------------------


# Fix remaining dtypes.
df["DSP"] = df["DSP"].astype("string")
df["Source_File"] = df["Source_File"].astype("string")
df["UPC"] = df["UPC"].astype("Int64").astype("string") #.astype("Int64") to remove the decimal

# Convert dates to datetime.
df["Report_Start_Date"] = pd.to_datetime(df["Report_Start_Date"], dayfirst=True).dt.normalize()
df["Report_End_Date"] = pd.to_datetime(df["Report_End_Date"], dayfirst=True).dt.normalize()

df_apple_mar24_clean = df
df_apple_mar24_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Artist             150000 non-null  string
 1   Label              150000 non-null  string
 2   Song_Title         150000 non-null  string
 3   ISRC               150000 non-null  string
 4   Album              150000 non-null  string
 5   UPC                150000 non-null  string
 6   Territory          150000 non-null  string
 7   Subscription_Type  150000 non-null  string
 8   Plays              150000 non-null  int64
 9   Earnings           150000 non-null  float64
 10  Currency_Code      150000 non-null  string
 11  Report_Start_Date  150000 non-null  datetime64[us]
 12  Report_End_Date    150000 non-null  datetime64[us]
 13  DSP                150000 non-null  string
 14  Source_File        150000 non-null  string
dtypes: datetime64[us](2), float64(1), int64(1), string(11)
memory usage: 41.1 MB

### deezer_jan24_raw

In [ ]:
df_deezer_jan24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Artiste          149998 non-null  str
 1   Label            149997 non-null  str
 2   Titre            149998 non-null  str
 3   ISRC             150000 non-null  str
 4   Album            149998 non-null  str
 5   UPC              149999 non-null  float64
 6   Pays             150000 non-null  str
 7   Type_Compte      150000 non-null  str
 8   Ecoutes          150000 non-null  int64
 9   Revenus          150000 non-null  float64
 10  Devise           150000 non-null  str
 11  Date_Debut       150000 non-null  str
 12  Date_Fin         150000 non-null  str
 13  Deezer_Track_ID  150000 non-null  int64
dtypes: float64(2), int64(2), str(10)
memory usage: 36.9 MB

- 2 'Artiste' null
- 3 'Label' null
- 2 'Titre' null
- 2 'Album' null
- 1 'UPC' null

In [26]:
# Remove duplicates.
df = df_deezer_jan24_raw.drop_duplicates()

# Drop columns not required in the final schema.
df = df.drop(columns=["Deezer_Track_ID"])

# Cast to string and strip whitespace.
for col in ["Artiste", "Label", "Titre", "ISRC", "Album", "Pays", "Type_Compte", "Devise"]:
    df[col] = df[col].astype("string").str.strip()

# DSP and Source columns creation.
df["DSP"] = "deezer"
df["Source_File"] = "deezer_jan24_raw.csv"

#-----------------------------------------------------------------------------
# Fill missing Label using dim_track as a lookup.
isrc_to_label = (
    df_dim_track[["ISRC", "Label"]]
    .assign(ISRC=lambda x: x["ISRC"].astype("string"))
    .set_index("ISRC")["Label"]
)

# Fill missing Label using the lookup.
df["Label"] = df["Label"].fillna(df["ISRC"].map(isrc_to_label))

#---------
# Fill missing Titre using dim_track as a lookup.
isrc_to_titre = (
    df_dim_track[["ISRC", "Track"]]
    .assign(ISRC=lambda x: x["ISRC"].astype("string"))
    .set_index("ISRC")["Track"]
)
# Fill missing Titre using the lookup.
df["Titre"] = df["Titre"].fillna(df["ISRC"].map(isrc_to_titre))


#---------

# Fill missing Album using dim_track as a lookup.
isrc_to_album = (
    df_dim_track[["ISRC", "Album"]]
    .assign(ISRC=lambda x: x["ISRC"].astype("string"))
    .set_index("ISRC")["Album"]
)

# Fill missing Album using the lookup.
df["Album"] = df["Album"].fillna(df["ISRC"].map(isrc_to_album))

#---------
# Fill missing UPC using dim_track as a lookup.
isrc_to_upc = (
    df_dim_track[["ISRC", "UPC"]]
    .assign(ISRC=lambda x: x["ISRC"].astype("string"))
    .set_index("ISRC")["UPC"]
)

# Fill missing Album using the lookup.
df["UPC"] = df["UPC"].fillna(df["ISRC"].map(isrc_to_upc))

#---------
# Fill missing Artiste using dim_track as a lookup.
isrc_to_artiste = (
    df_dim_track[["ISRC", "Artist"]]
    .assign(ISRC=lambda x: x["Artist"].astype("string"))
    .set_index("ISRC")["Artist"]
)

# Fill missing Artiste using the lookup.
df["Artiste"] = df["Artiste"].fillna(df["ISRC"].map(isrc_to_label))

#-----------------------------------------------------------------------------


# Fix remaining dtypes.
df["DSP"] = df["DSP"].astype("string")
df["Source_File"] = df["Source_File"].astype("string")
df["UPC"] = df["UPC"].astype("Int64").astype("string") #.astype("Int64") to remove the decimal

# Convert dates to datetime.
df["Date_Debut"] = pd.to_datetime(df["Date_Debut"], dayfirst=True).dt.normalize()
df["Date_Fin"] = pd.to_datetime(df["Date_Fin"], dayfirst=True).dt.normalize()

df_deezer_jan24_clean = df
df_deezer_jan24_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 15 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Artiste      150000 non-null  string
 1   Label        150000 non-null  string
 2   Titre        150000 non-null  string
 3   ISRC         150000 non-null  string
 4   Album        150000 non-null  string
 5   UPC          150000 non-null  string
 6   Pays         150000 non-null  string
 7   Type_Compte  150000 non-null  string
 8   Ecoutes      150000 non-null  int64
 9   Revenus      150000 non-null  float64
 10  Devise       150000 non-null  string
 11  Date_Debut   150000 non-null  datetime64[us]
 12  Date_Fin     150000 non-null  datetime64[us]
 13  DSP          150000 non-null  string
 14  Source_File  150000 non-null  string
dtypes: datetime64[us](2), float64(1), int64(1), string(11)
memory usage: 40.8 MB

### deezer_feb24_raw

In [19]:
df_deezer_feb24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Artiste          149996 non-null  str
 1   Label            149994 non-null  str
 2   Titre            149998 non-null  str
 3   ISRC             149996 non-null  str
 4   Album            149998 non-null  str
 5   UPC              149999 non-null  float64
 6   Pays             150000 non-null  str
 7   Type_Compte      150000 non-null  str
 8   Ecoutes          150000 non-null  int64
 9   Revenus          150000 non-null  float64
 10  Devise           150000 non-null  str
 11  Date_Debut       150000 non-null  str
 12  Date_Fin         150000 non-null  str
 13  Deezer_Track_ID  150000 non-null  int64
dtypes: float64(2), int64(2), str(10)
memory usage: 36.9 MB

In [36]:
null_counts = df_deezer_feb24_raw.isna().sum()
print('null values count:')
print(null_counts[null_counts > 0])

null values count:
Artiste    4
Label      6
Titre      2
ISRC       4
Album      2
UPC        1
dtype: int64

In [38]:
# Remove duplicates.
df = df_deezer_feb24_raw.drop_duplicates()

# Drop columns not required in the final schema.
df = df.drop(columns=["Deezer_Track_ID"])

# Cast to string and strip whitespace.
for col in ["Artiste", "Label", "Titre", "ISRC", "Album", "Pays", "Type_Compte", "Devise"]:
    df[col] = df[col].astype("string").str.strip()

# DSP and Source columns creation.
df["DSP"] = "deezer"
df["Source_File"] = "deezer_feb24_raw.csv"

#-----------------------------------------------------------------------------
# Fill missing Label using dim_track as a lookup.
isrc_to_label = (
    df_dim_track[["ISRC", "Label"]]
    .assign(ISRC=lambda x: x["ISRC"].astype("string"))
    .set_index("ISRC")["Label"]
)

# Fill missing Label using the lookup.
df["Label"] = df["Label"].fillna(df["ISRC"].map(isrc_to_label))

#---------
# Fill missing Titre using dim_track as a lookup.
isrc_to_titre = (
    df_dim_track[["ISRC", "Track"]]
    .assign(ISRC=lambda x: x["ISRC"].astype("string"))
    .set_index("ISRC")["Track"]
)
# Fill missing Titre using the lookup.
df["Titre"] = df["Titre"].fillna(df["ISRC"].map(isrc_to_titre))


#---------

# Fill missing Album using dim_track as a lookup.
isrc_to_album = (
    df_dim_track[["ISRC", "Album"]]
    .assign(ISRC=lambda x: x["ISRC"].astype("string"))
    .set_index("ISRC")["Album"]
)

# Fill missing Album using the lookup.
df["Album"] = df["Album"].fillna(df["ISRC"].map(isrc_to_album))

#---------
# Fill missing UPC using dim_track as a lookup.
isrc_to_upc = (
    df_dim_track[["ISRC", "UPC"]]
    .assign(ISRC=lambda x: x["ISRC"].astype("string"))
    .set_index("ISRC")["UPC"]
)

# Fill missing UPC using the lookup.
df["UPC"] = df["UPC"].fillna(df["ISRC"].map(isrc_to_upc))

#---------
# Fill missing Artiste using dim_track as a lookup.
isrc_to_artiste = (
    df_dim_track[["ISRC", "Artist"]]
    .assign(ISRC=lambda x: x["Artist"].astype("string"))
    .set_index("ISRC")["Artist"]
)

# Fill missing Artiste using the lookup.
df["Artiste"] = df["Artiste"].fillna(df["ISRC"].map(isrc_to_label))

#---------
# Build a (ArtistName, TrackTitle) to ISRC lookup from dim_track.
# Lowercased on both sides to ensure the matching with the raw data.
artist_track_to_isrc = (
    df_dim_track[["Artist", "Track", "ISRC"]]
    .assign(
        Artist=lambda x: x["Artist"].astype("string").str.lower(),
        Track=lambda x: x["Track"].astype("string").str.lower(),
        ISRC=lambda x: x["ISRC"].astype("string"),
    )
    .set_index(["Artist", "Track"])["ISRC"]
    .to_dict()
)

# Fill missing ISRCs using the lookup.
df["ISRC"] = df["ISRC"].fillna(
    df.apply(lambda row: artist_track_to_isrc.get(
        (row["Artiste"].lower(), row["Titre"].lower())
    ), axis=1)
)

#-----------------------------------------------------------------------------


# Fix remaining dtypes.
df["DSP"] = df["DSP"].astype("string")
df["Source_File"] = df["Source_File"].astype("string")
df["UPC"] = df["UPC"].astype("Int64").astype("string") #.astype("Int64") to remove the decimal

# Convert dates to datetime.
df["Date_Debut"] = pd.to_datetime(df["Date_Debut"], dayfirst=True).dt.normalize()
df["Date_Fin"] = pd.to_datetime(df["Date_Fin"], dayfirst=True).dt.normalize()

df_deezer_feb24_clean = df
df_deezer_feb24_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 15 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Artiste      150000 non-null  string
 1   Label        150000 non-null  string
 2   Titre        150000 non-null  string
 3   ISRC         150000 non-null  string
 4   Album        150000 non-null  string
 5   UPC          150000 non-null  string
 6   Pays         150000 non-null  string
 7   Type_Compte  150000 non-null  string
 8   Ecoutes      150000 non-null  int64
 9   Revenus      150000 non-null  float64
 10  Devise       150000 non-null  string
 11  Date_Debut   150000 non-null  datetime64[us]
 12  Date_Fin     150000 non-null  datetime64[us]
 13  DSP          150000 non-null  string
 14  Source_File  150000 non-null  string
dtypes: datetime64[us](2), float64(1), int64(1), string(11)
memory usage: 40.8 MB

### deezer_mar24_raw

In [52]:
df_deezer_mar24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Artiste          149999 non-null  str
 1   Label            150000 non-null  str
 2   Titre            149999 non-null  str
 3   ISRC             149998 non-null  str
 4   Album            150000 non-null  str
 5   UPC              150000 non-null  float64
 6   Pays             150000 non-null  str
 7   Type_Compte      150000 non-null  str
 8   Ecoutes          150000 non-null  int64
 9   Revenus          150000 non-null  float64
 10  Devise           150000 non-null  str
 11  Date_Debut       150000 non-null  str
 12  Date_Fin         150000 non-null  str
 13  Deezer_Track_ID  150000 non-null  int64
dtypes: float64(2), int64(2), str(10)
memory usage: 36.9 MB

In [53]:
null_counts = df_deezer_mar24_raw.isna().sum()
print('null values count:')
print(null_counts[null_counts > 0])

null values count:
Artiste    1
Titre      1
ISRC       2
dtype: int64

In [72]:
# Remove duplicates.
df = df_deezer_mar24_raw.drop_duplicates()

# Drop columns not required in the final schema.
df = df.drop(columns=["Deezer_Track_ID"])

# Cast to string and strip whitespace.
for col in ["Artiste", "Label", "Titre", "ISRC", "Album", "Pays", "Type_Compte", "Devise"]:
    df[col] = df[col].astype("string").str.strip()

# DSP and Source columns creation.
df["DSP"] = "deezer"
df["Source_File"] = "deezer_mar24_raw.csv"

# build a couple of reusable lookup objects from the master table
dim = df_dim_track.copy()

# cast columns to string once so that downstream mappings are consistent
for c in ["UPC", "Artist", "Track", "ISRC"]:
    dim[c] = dim[c].astype("string")

# ------------------------------------------------------------------
# UPC to Artist
upc_to_artiste = (
    dim
    .drop_duplicates("UPC", keep="last")
    .set_index("UPC")["Artist"]
)

# ISRC to Track (used later to populate `Titre`)
isrc_to_titre = dim.set_index("ISRC")["Track"]

# (artist, upc) to ISRC lookup; lowercase both sides for matching
artist_upc_to_isrc = (
    dim
    .assign(
        Artist_lc=dim["Artist"].str.lower(),
        UPC_lc=dim["UPC"].str.lower(),
    )
    .dropna(subset=["Artist_lc", "UPC_lc", "ISRC"])
    .set_index(["Artist_lc", "UPC_lc"])["ISRC"]
    .to_dict()
)
# ------------------------------------------------------------------

# fill the missing values in the deezer_mar24 dataframe
df["Artiste"] = df["Artiste"].fillna(df["UPC"].map(upc_to_artiste))

def _lookup_isrc(row):
    artist = row["Artiste"].lower() if pd.notna(row["Artiste"]) else ""
    upc    = str(row["UPC"]).lower() if pd.notna(row["UPC"]) else ""
    return artist_upc_to_isrc.get((artist, upc))

df["ISRC"] = df["ISRC"].fillna(df.apply(_lookup_isrc, axis=1))
df["Titre"] = df["Titre"].fillna(df["ISRC"].map(isrc_to_titre))


# Fix remaining dtypes.
df["DSP"] = df["DSP"].astype("string")
df["Source_File"] = df["Source_File"].astype("string")
df["UPC"] = df["UPC"].astype("Int64").astype("string") #.astype("Int64") to remove the decimal

# Convert dates to datetime.
df["Date_Debut"] = pd.to_datetime(df["Date_Debut"], dayfirst=True).dt.normalize()
df["Date_Fin"] = pd.to_datetime(df["Date_Fin"], dayfirst=True).dt.normalize()

df = df.dropna(subset=["ISRC", "Artiste"])


df_deezer_mar24_clean = df
df_deezer_mar24_clean.info()

<class 'pandas.DataFrame'>
Index: 149999 entries, 0 to 149999
Data columns (total 15 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Artiste      149999 non-null  string
 1   Label        149999 non-null  string
 2   Titre        149999 non-null  string
 3   ISRC         149999 non-null  string
 4   Album        149999 non-null  string
 5   UPC          149999 non-null  string
 6   Pays         149999 non-null  string
 7   Type_Compte  149999 non-null  string
 8   Ecoutes      149999 non-null  int64
 9   Revenus      149999 non-null  float64
 10  Devise       149999 non-null  string
 11  Date_Debut   149999 non-null  datetime64[us]
 12  Date_Fin     149999 non-null  datetime64[us]
 13  DSP          149999 non-null  string
 14  Source_File  149999 non-null  string
dtypes: datetime64[us](2), float64(1), int64(1), string(11)
memory usage: 42.0 MB

### spotify_jan24_raw

In [77]:
df_spotify_jan24_raw.head(2)

,artist_name,label_name,track_title,isrc,album_title,upc,country_code,stream_type,streams,royalty_amount,currency,period_start,period_end
0,Wiggins & Ball,Warp Records,Function-Based Mobile Challenge,NLSXD1849510,Re-Contextualize Integrated Infrastructures,3.420405e+11,CA,Premium,436,2.13,USD,01/01/2024,31/01/2024
1,Lee & Chung,Harris-Greer Entertainment,Managed Foreground Hub,USMT51887504,Grow B2C Paradigms - Single,7.607030e+12,AU,Premium,621,1.93,USD,01/01/2024,31/01/2024

In [106]:

df_spotify_jan24_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   artist_name     149994 non-null  str
 1   label_name      149995 non-null  str
 2   track_title     149997 non-null  str
 3   isrc            149996 non-null  str
 4   album_title     149999 non-null  str
 5   upc             150000 non-null  float64
 6   country_code    150000 non-null  str
 7   stream_type     150000 non-null  str
 8   streams         150000 non-null  int64
 9   royalty_amount  150000 non-null  float64
 10  currency        150000 non-null  str
 11  period_start    150000 non-null  str
 12  period_end      150000 non-null  str
dtypes: float64(2), int64(1), str(10)
memory usage: 35.8 MB

In [76]:
null_counts = df_spotify_jan24_raw.isna().sum()
print('null values count:')
print(null_counts[null_counts > 0])

null values count:
artist_name    6
label_name     5
track_title    3
isrc           4
album_title    1
dtype: int64

In [28]:
# Fill missing album_title using dim_Album as a lookup.
isrc_to_Album = (
    df_dim_track[["ISRC", "Album"]]
    .assign(ISRC=lambda x: x["ISRC"].astype("string"))
.drop_duplicates(subset=["ISRC"], keep="last")
.set_index("ISRC")["Album"]
)

# Fill missing album_title using the lookup.
df["album_title"] = df["album_title"].fillna(df["isrc"].map(isrc_to_Album))

In [29]:
# Remove duplicates.
df = df_spotify_jan24_raw.drop_duplicates()

# Cast to string and strip whitespace.
for col in ["artist_name", "label_name", "track_title", "isrc", "album_title", "country_code", "stream_type", "currency"]:
    df[col] = df[col].astype(str).str.strip()

# DSP and Source columns creation.
df["DSP"] = "Spotify"
df["Source_File"] = "spotify_jan24_raw.csv"

#-----------------------------------------------------------------------------

# Fill missing album_title using dim_Album as a lookup.
isrc_to_Album = (
    df_dim_track[["ISRC", "Album"]]
    .assign(ISRC=lambda x: x["ISRC"].astype("string"))
.drop_duplicates(subset=["ISRC"], keep="last")
.set_index("ISRC")["Album"]
)

# Fill missing album_title using the lookup.
df["album_title"] = df["album_title"].fillna(df["isrc"].map(isrc_to_Album))


#--------
# Fill missing artist_name using dim_track as a lookup.
isrc_to_artist = (
    df_dim_track[["ISRC", "Artist"]]
    .assign(ISRC=lambda x: x["ISRC"].astype("string"))
.drop_duplicates(subset=["ISRC"], keep="last")
.set_index("ISRC")["Artist"]
)

# Fill missing artist_name using the lookup.
df["artist_name"] = df["artist_name"].fillna(df["isrc"].map(isrc_to_artist))


#---------
# Fill missing track_title using dim_track as a lookup.
isrc_to_Track = (
    df_dim_track[["ISRC", "Track"]]
    .assign(ISRC=lambda x: x["ISRC"].astype("string"))
.drop_duplicates(subset=["ISRC"], keep="last")
.set_index("ISRC")["Track"]
)

# Fill missing track_title using the lookup.
df["track_title"] = df["track_title"].fillna(df["isrc"].map(isrc_to_Track))

#---------


# Fill missing label_name using dim_track as a lookup.
isrc_to_label = (
    df_dim_track[["ISRC", "Label"]]
    .assign(ISRC=lambda x: x["ISRC"].astype("string"))
.drop_duplicates(subset=["ISRC"], keep="last")
.set_index("ISRC")["Label"]
)

# Fill missing label_name using the lookup.
df["label_name"] = df["label_name"].fillna(df["isrc"].map(isrc_to_label))

#---------
# Build a (artist_name, track_title) to isrc lookup from dim_track.
# Lowercased on both sides to ensure the matching with the raw data.
artist_track_to_isrc = (
    df_dim_track[["Artist", "Track", "ISRC"]]
    .assign(
        Artist=lambda x: x["Artist"].astype("string").str.lower(),
        Track=lambda x: x["Track"].astype("string").str.lower(),
        isrc=lambda x: x["ISRC"].astype("string"),
    )
    .set_index(["Artist", "Track"])["isrc"]
    .to_dict()
)

# Fill missing isrcs using the lookup.
df["isrc"] = df["isrc"].fillna(
    df.apply(
        lambda row: artist_track_to_isrc.get((
            row["artist_name"].lower() if pd.notna(row["artist_name"]) else "",
            row["track_title"].lower() if pd.notna(row["track_title"]) else "",
        )),
        axis=1,
    )
)


#-----------------------------------------------------------------------------

# Fix remaining dtypes.
df["DSP"] = df["DSP"].astype("string")
df["Source_File"] = df["Source_File"].astype("string")
df["upc"] = df["upc"].astype("Int64").astype("string") #.astype("Int64") to remove the decimal

str_cols = ["artist_name", "label_name", "track_title", "isrc", "album_title", "country_code", "stream_type", "currency"]
df[str_cols] = df[str_cols].astype("string")

# Convert dates to datetime.
df["period_start"] = pd.to_datetime(df["period_start"], dayfirst=True).dt.normalize()
df["period_end"] = pd.to_datetime(df["period_end"], dayfirst=True).dt.normalize()

df_spotify_jan24_clean = df
df_spotify_jan24_clean.info()

<class 'pandas.DataFrame'>
Index: 149995 entries, 0 to 149999
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   artist_name     149995 non-null  string
 1   label_name      149995 non-null  string
 2   track_title     149995 non-null  string
 3   isrc            149995 non-null  string
 4   album_title     149995 non-null  string
 5   upc             149995 non-null  string
 6   country_code    149995 non-null  string
 7   stream_type     149995 non-null  string
 8   streams         149995 non-null  int64
 9   royalty_amount  149995 non-null  float64
 10  currency        149995 non-null  string
 11  period_start    149995 non-null  datetime64[us]
 12  period_end      149995 non-null  datetime64[us]
 13  DSP             149995 non-null  string
 14  Source_File     149995 non-null  string
dtypes: datetime64[us](2), float64(1), int64(1), string(11)
memory usage: 42.2 MB